export const Blogs = [
  {
    id: "01",
    date: "October 15, 2025",
    title: "Use Mongoose with Next-Auth Without an Adapter! 🚀",
    link: "use-mongoose-with-next-auth-without-an-adapter",
    blogImg: "/mongose.jpg",
    description:
      "Are you ready to supercharge your Next.js authentication setup without the need for a traditional adapter? You can now seamlessly integrate Mongoose into your Next-Auth.js configuration with ease. Here's a step-by-step guide on how to do it using Next-Auth.js callbacks:",
    tags: ["mongoose", "Next-Auth", "Next.Js"],
    maintags: "next-auth",
  },
  {
    id: "02",
    date: "October 14, 2025",
    title: "Is Really Bun js can beat node.js & deno.js ⚡️",
    link: "is-really-bunjs-can-beat-nodejs-and-denojs",
    blogImg: "/bun-killing-nodejs.jpg",
    description: `Bun.js core is written in Zig, which gives it a significant performance advantage over Node.js and Deno.js, which are both written in JavaScript.`,
    explainCode: [],
    tags: ["bunjs", "Next-Auth", "Next.Js", "deno.js"],
    maintags: "bunjs",
  },
  {
    id: "03",
    date: "October 8, 2025",
    title: "🔐 Difference between nextAuth, firebase and supabase.",
    link: "difference-between-nextauth-firebase-and-supabase",
    blogImg: "/authentication.jpg",
    description: `When it comes to building secure and efficient authentication systems for your web applications, you have choices. Each option has its strengths and considerations:`,
    tags: ["firbase", "Next-Auth", "supabase"],
    maintags: "auth",
  },
  {
    id: "04",
    date: "September 9, 2023",
    title: "Why a Website is Crucial for Your Business 🌐",
    link: "why-a-website-is-crucial-for-your-business",
    blogImg: "/why-website.png",
    description: `In today's digital age, having a strong online presence is non-negotiable for businesses of all sizes. And at the heart of that online presence is your website. Here are a few compelling reasons why having a website is absolutely essential:`,
    tags: ["website", "web design", "development"],
    maintags: "website",
  },
];
