export const projects = [
  {
    name: "Distrokings",
    client: "Grow",
    description: "A partnership between Google & SN37.",
    src: "/projects/distrokings.jpg",
    hoverscr: "",
    link: "https://distrokings.com/",
  },
  {
    name: "Profitables",
    client: "Decimal",
    description: "Portfolio site for Decimal.",
    src: "/projects/profitables.jpg",
    hoverscr: "",
    link: "https://profitables.vercel.app/",
  },
  {
    name: "Topserve-copiers",
    client: "analogueagency",
    description: "New web design for the blockchain investment fund Maven 11.",
    src: "/projects/topserve.jpg",
    hoverscr: "",
    link: "https://topserve-copiers.co.uk/",
  },
  {
    name: "Labramart",
    client: "Wix Playground",
    description: "Wix Playground is powered by the Wix.com design team.",
    src: "/projects/labramart.jpg",
    hoverscr: "",
    link: "",
  },
  {
    name: "Distrokings Logo",
    client: "POWELL—STUDIO",
    description: "The online presence for Powell—Studio.",
    src: "/projects/distrokingslogo.png",
    hoverscr: "/projects/distrokingslogo.png",
    link: "https://distrokings.com/",
  },
  {
    name: "Roofing up",
    client: "ET Studio",
    description: "An Italian animation studio.",
    src: "/projects/roofingup.jpg",
    hoverscr: "",
    link: "https://roofingupfl.com/",
  },
];
